[package]
# OpenRetailDataMigrator
name = "odm"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["cargo"] }
open-stock = "0.1.4"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }
uuid = "1.3.1"
